import { describe, expect, it } from "vitest";
import { addDays } from "../domain/rules/dates.js";
import { assignmentKey } from "../domain/schedule/types.js";
import {
  buildManualEditValidationContext,
  validateManualSet,
} from "../domain/schedule/manual-edit-validator.js";
import { operationalBalancer } from "../domain/schedule/operational-balancer.js";
import { countAutoCommonFolgas } from "../domain/schedule/real-schedule-folga-metrics.js";
import { realScheduleEngine } from "../domain/schedule/real-schedule-engine.js";
import { scheduleGenerationEngine } from "../domain/schedule/schedule-generation-engine.js";
import {
  freshWorkspace,
  minimalPaoInput,
  paoUuid,
  realPaoUuid,
} from "./schedule-slices/slice-helpers.js";
import { realisticGenerationInput } from "./realistic-fixtures.js";

const MONTH_DAYS = Array.from({ length: 30 }, (_, i) => `2026-06-${String(i + 1).padStart(2, "0")}`);

function motorReport(result: ReturnType<typeof realScheduleEngine.generate>) {
  return result.summary.realMotorReport as {
    commonFolgaAutoGenerated?: boolean;
    socialFolgaGenerated?: number;
    groupedApaoFolgaGenerated?: number;
    emptyDaysLeftForManualEditing?: number;
    t8PairsWithoutNdCount?: number;
  };
}

function commonFolgas(result: ReturnType<typeof realScheduleEngine.generate>): number {
  return result.allocations.filter(
    (a) =>
      a.label === "FOLGA" &&
      result.assignments.some((s) => s.employeeUuid === a.employeeUuid) === false &&
      !["FOLGA SOCIAL", "FOLGA AGRUPADA", "FOLGA PEDIDA"].includes(a.label),
  ).length;
}

function emptyPaoDays(result: ReturnType<typeof realScheduleEngine.generate>, uuid: string): string[] {
  return MONTH_DAYS.filter((day) => {
    const hasShift = result.assignments.some((a) => a.employeeUuid === uuid && a.date === day);
    const hasAlloc = result.allocations.some((a) => a.employeeUuid === uuid && a.date === day);
    return !hasShift && !hasAlloc;
  });
}

describe("CORREÇÃO REAL_V1 — folga comum manual", () => {
  it("0. Gerar escala PAO não aloca APAO (use botão Gerar Escala APAO)", () => {
    const input = realisticGenerationInput();
    const result = realScheduleEngine.generate(input);
    const apaoIds = new Set(
      input.employees.filter((e) => e.employee.role === "APAO").map((e) => e.uuid),
    );
    const apaoAssignments = result.assignments.filter((a) => apaoIds.has(a.employeeUuid));
    const apaoAllocations = result.allocations.filter((a) => apaoIds.has(a.employeeUuid));
    expect(apaoAssignments.length).toBe(0);
    expect(apaoAllocations.length).toBe(0);
  });

  it("1. Gerar escala não cria FOLGA comum automaticamente", () => {
    const result = realScheduleEngine.generate(realisticGenerationInput());
    const report = motorReport(result);

    expect(report.commonFolgaAutoGenerated).toBe(false);

    const ws = freshWorkspace(realisticGenerationInput());
    ws.applyHardBlocks();
    ws.realV1ManualCommonFolga = true;
    realScheduleEngine.execute(ws);
    expect(countAutoCommonFolgas(ws)).toBe(0);

    const autoCommon = result.allocations.filter(
      (a) =>
        a.label === "FOLGA" &&
        realisticGenerationInput().employees.some(
          (e) => e.uuid === a.employeeUuid && e.employee.role === "PAO",
        ),
    );
    expect(autoCommon.length).toBe(0);
    expect(commonFolgas(result)).toBe(0);
  });

  it("2. Gerar escala cria 1 par FS (sáb+dom) por PAO", () => {
    const input = realisticGenerationInput();
    const result = realScheduleEngine.generate(input);
    const report = motorReport(result);
    const paoCount = input.employees.filter((e) => e.employee.role === "PAO").length;

    expect(report.socialFolgaGenerated).toBe(paoCount * 2);
    for (const e of input.employees.filter((x) => x.employee.role === "PAO")) {
      const fs = result.allocations.filter(
        (a) => a.employeeUuid === e.uuid && a.label === "FOLGA SOCIAL",
      );
      expect(fs.length).toBe(2);
    }
  });

  it("3. Gerar escala não cria FA automaticamente (manual na escala)", () => {
    const result = realScheduleEngine.generate(realisticGenerationInput());
    const report = motorReport(result);
    const fa = result.allocations.filter((a) => a.label === "FOLGA AGRUPADA");

    expect(report.groupedApaoFolgaGenerated).toBe(0);
    expect(fa.length).toBe(0);
  });

  it("3b. Gerar escala não cria VOO automaticamente", () => {
    const result = realScheduleEngine.generate(realisticGenerationInput());
    const voos = result.allocations.filter((a) => a.label === "VOO");
    expect(voos.length).toBe(0);
    expect(result.summary.realMotorReport?.flightsForDeficit ?? 0).toBe(0);
  });

  it("4. ND após T8/T8 continua aparecendo", () => {
    const result = realScheduleEngine.generate(minimalPaoInput(4));
    const report = motorReport(result);
    expect(report.t8PairsWithoutNdCount ?? 0).toBe(0);

    for (let i = 0; i < MONTH_DAYS.length - 1; i++) {
      const d0 = MONTH_DAYS[i]!;
      const d1 = MONTH_DAYS[i + 1]!;
      const t8d0 = result.assignments.filter((a) => a.date === d0 && a.shiftCode === "T8");
      const t8d1 = result.assignments.filter((a) => a.date === d1 && a.shiftCode === "T8");
      for (const a0 of t8d0) {
        if (!t8d1.some((a1) => a1.employeeUuid === a0.employeeUuid)) continue;
        const ndDay = addDays(d1, 1);
        const hasNd = result.allocations.some(
          (a) => a.employeeUuid === a0.employeeUuid && a.date === ndDay && a.label === "ND",
        );
        expect(hasNd).toBe(true);
      }
    }
  });

  it("5. Dias sem alocação permanecem vazios", () => {
    const result = realScheduleEngine.generate(realisticGenerationInput());
    const report = motorReport(result);
    const uuid = realPaoUuid(0);
    const empty = emptyPaoDays(result, uuid);

    expect(empty.length).toBeGreaterThan(0);
    expect(report.emptyDaysLeftForManualEditing).toBeGreaterThan(0);
  });

  it("6. Edição manual permite aplicar FOLGA em dia vazio após geração", () => {
    const input = minimalPaoInput(4);
    const ws = freshWorkspace(input);
    ws.applyHardBlocks();
    realScheduleEngine.execute(ws);

    const uuid = paoUuid(0);
    const did = ws.uuidToDomain.get(uuid)!;
    const emptyDay = ws.emptyDaysForPao(uuid).find((day) => {
      const prev = ws.planned.get(assignmentKey(did, addDays(day, -1)));
      const next = ws.planned.get(assignmentKey(did, addDays(day, 1)));
      return prev !== "T8" && next !== "T8";
    });
    expect(emptyDay).toBeDefined();

    const ctx = ws.toScheduleContext();
    const employees = input.employees.map((e) => ({
      id: e.uuid,
      name: e.employee.name,
      role: e.employee.role,
    }));
    const v = buildManualEditValidationContext({
      ctx,
      employees,
      shiftRestrictionRows: [],
      noFlightDates: input.noFlightDates ?? [],
      vacationDays: input.vacationDays,
      approvedDayOff: input.approvedDayOff,
      assignments: ws.toAssignments().map((a) => ({
        employeeId: a.employeeUuid,
        date: a.date,
        shiftCode: a.shiftCode,
      })),
      preAllocations: ws.allocations.map((a) => ({
        employeeId: a.employeeUuid,
        date: a.date,
        label: a.label,
      })),
      flightDays: input.flightDays,
    });
    const conflicts = validateManualSet(
      v,
      { employeeId: uuid, date: emptyDay! },
      "FOLGA",
    );
    expect(conflicts).toHaveLength(0);
  });

  it("7. Balanceador não insere FOLGA comum automaticamente no REAL_V1", () => {
    const input = realisticGenerationInput();
    const ws = freshWorkspace(input);
    ws.applyHardBlocks();
    ws.realV1ManualCommonFolga = true;
    realScheduleEngine.execute(ws);

    const beforeCommon = ws.allocations.filter((a) => a.label === "FOLGA").length;
    const report = operationalBalancer.balance(ws);
    const afterCommon = ws.allocations.filter((a) => a.label === "FOLGA").length;
    const folgaActions = report.actions.filter((a) => a.kind === "folga_inserted");

    expect(folgaActions.length).toBe(0);
    expect(afterCommon).toBe(beforeCommon);
  });

  it("8. REAL_V1 continua cobrindo T6/T7/T8", () => {
    const result = scheduleGenerationEngine.generate(realisticGenerationInput());
    const t6 = result.assignments.filter((a) => a.shiftCode === "T6").length;
    const t7 = result.assignments.filter((a) => a.shiftCode === "T7").length;
    const t8 = result.assignments.filter((a) => a.shiftCode === "T8").length;

    expect(t6).toBeGreaterThan(0);
    expect(t7).toBeGreaterThan(0);
    expect(t8).toBeGreaterThan(0);
    expect(result.summary.coverageGaps ?? 0).toBe(0);
  });
});
