import type { GenerationWorkspace } from "./generation-workspace.js";

export interface RealV1FolgaReport {
  commonFolgaAutoGenerated: false;
  socialFolgaGenerated: number;
  groupedApaoFolgaGenerated: number;
  emptyDaysLeftForManualEditing: number;
}

/** Métricas de folga para relatório REAL_V1 (folga comum manual). */
export function buildRealV1FolgaReport(ws: GenerationWorkspace): RealV1FolgaReport {
  let socialFolgaGenerated = 0;
  let groupedApaoFolgaGenerated = 0;

  for (const a of ws.allocations) {
    if (a.label === "FOLGA SOCIAL") socialFolgaGenerated++;
    if (a.label === "FOLGA AGRUPADA") groupedApaoFolgaGenerated++;
  }

  let emptyDaysLeftForManualEditing = 0;
  for (const c of ws.paoEmps) {
    emptyDaysLeftForManualEditing += ws.emptyDaysForPao(c.uuid).length;
  }

  return {
    commonFolgaAutoGenerated: false,
    socialFolgaGenerated,
    groupedApaoFolgaGenerated,
    emptyDaysLeftForManualEditing,
  };
}

/** Folga comum (label exata "FOLGA") gerada pelo motor — não inclui FS/FA/FP/férias. */
export function countAutoCommonFolgas(ws: GenerationWorkspace): number {
  return ws.allocations.filter((a) => {
    const isPao = ws.paoEmps.some((p) => p.uuid === a.employeeUuid);
    return isPao && a.label === "FOLGA";
  }).length;
}
